site_name: Портфолио
site_url: https://imaskot.github.io/


theme:
  name: material
  language: ru
  palette:
    scheme: slate
    primary: black
    accent: deep-orange
  features:
    - navigation.tabs
    - header.autohide
    - content.code.copy


nav:
  - Обо мне: index.md
  - Лабораторные работы:
      - Введение: projects.md
      - Лабораторная 1: lab1.md
      - Лабораторная 2: lab2.md
      - Лабораторная 3: lab3.md
  - Контакты: contact.md

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
copyright: Copyright &copy; 2026 Максим Седов